rise_info/contents/urls.py
from django.urls import path
from contents import views

urlpatterns = [
    path("new/", views.content_new, name="content_new"),
    path("<int:content_id>/", views.content_detail, name="content_detail"),
    path("<int:content_id>/edit/", views.content_edit, name="content_edit"),
    path("content/del/<int:content_id>/",
         views.content_del, name="content_del"),
    path("content/up/<int:content_id>/", views.content_up, name="content_up"),
    path("content/down/<int:content_id>/",
         views.content_down, name="content_down"),
    path("menu/list/", views.menu_list, name="menu_list"),
    path("menu/new/", views.menu_new, name="menu_new"),
    path("menu/new/<int:menu_id>/", views.menu_edit, name="menu_edit"),
    path("menu/up/<int:menu_id>/", views.menu_up, name="menu_up"),
    path("menu/down/<int:menu_id>/", views.menu_down, name="menu_down"),
    path("menu/del/<int:menu_id>/", views.menu_del, name="menu_del"),
    path("<int:content_id>/comment/", views.add_comment, name="content_comment"),
    path("<int:content_id>/comment_del/<int:comment_id>/",
          views.del_comment, name="content_del_comment"),

]

rise_info/eqs/urls.py
from django.urls import path

from . import views

app_name = 'eqs'

urlpatterns = [
    path('eqtypes/', views.file_upload, name='eqtype'),
    path('eqtypes/download/', views.file_downnload, name='eqtype_download'),
    path("eqtypes/<slug:slug>/del/", views.eqtype_del, name="eqtype_del"),
    path('eqtypes/api/posts/', views.api_posts_get, name='api_posts_get'),
    path('eqtypes/new/', views.eqtype_new, name='eqtype_new'),
    path('eqclass/new/', views.eq_class_new, name='eqclass_new'),
]

rise_info/rise_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                # mdeditor
from django.conf.urls import handler400, url    # mdeditor
from django.conf.urls.static import static      # mdeditor
# import debug_toolbar # django toolbar

from rise_info import views

urlpatterns = [
    path("", views.top, name="top"),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("addresses/", include("addresses.urls")),
    path("contents/", include("contents.urls")),
    path("failuer_reports/", include("failuer_reports.urls")),
    path('infos/', include('infos.urls')),
    path('offices/', include('offices.urls')),
    path('eqs/', include('eqs.urls')),
    path('tech_support/', include('tech_supports.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),  # mdeditor
]

handler404 = 'rise_info.views.handler404'
if settings.DEBUG:  # mdeditor
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)    # mdeditor
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.GYOMUSHIEN_URL,
                          document_root=settings.GYOMUSHIEN_ROOT)

# django toolbar
# if settings.DEBUG:
#    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

rise_info/contents/models.py
from django.db import models
from django.db.models import Max

from addresses.models import Addresses
from rise_info.baseModels import CommonInfo, BaseAttachment, BaseManager, BaseCommnets


class Menu(models.Model):
    objects = BaseManager()
    menu_title = models.CharField('タイトル', max_length=24)
    sort_num = models.IntegerField(
        verbose_name='並び順', default=1, db_index=True)

    def __str__(self):
        return self.menu_title

    def create(self, *args, **kwargs):
        all_menu = Menu.objects.all()
        if all_menu.filter(sort_num=self.sort_num).count() > 0:
            max_val = all_menu.aggregate(Max('sort_num'))
            self.sort_num = max_val['sort_num__max'] + 1
        super(Menu, self).save(**kwargs)

    def save(self, *args, **kwargs):
        super(Menu, self).save(**kwargs)

    def replace_sort_num(self, subject: 'Menu', *args, **kwargs):
        if subject:
            self.sort_num, subject.sort_num = subject.sort_num, self.sort_num
            Menu.objects.bulk_update([self, subject], fields=['sort_num'])
        else:
            raise ValueError('対象が空です')

    class Meta:
        db_table = 'menus'
        verbose_name = 'メニュー'
        verbose_name_plural = 'メニュー一覧'

class Contents(CommonInfo):
    is_rich_text = models.BooleanField(
        verbose_name='リッチテキスト有効', default=False, help_text='内容のリッチテキスト有効/無効')
    addresses = models.ManyToManyField(
        Addresses, verbose_name='受信アドレス', null=True, blank=True,
        related_name='contents')

    def delete(self, *args, **kwargs):
        for attachment in self.attachmentfile_set.all():
            attachment.delete()
        return super().delete(*args, **kwargs)

    def save(self, *args, **kwargs):
        return super().save(self, *args, **kwargs)

    class Meta:
        db_table = 'contents'
        verbose_name = '管技wikiコンテンツ(全データ)'
        verbose_name_plural = '管技wikiコンテンツ一覧(全データ)'

class AttachmentFile(BaseAttachment):
    info = models.ForeignKey(Contents, on_delete=models.CASCADE)
    upload_path = 'contents'

    class Meta:
        db_table = 'content_attachment'
        verbose_name = '管技wiki添付ファイル'
        verbose_name_plural = '管技wiki添付ファイル一覧'


class ContentComments(BaseCommnets):
   content = models.ForeignKey(
       Contents, related_name='contentComment', on_delete=models.CASCADE)
   upload_path = 'content_comments'
   class Meta:
       db_table = 'content_comments'
       verbose_name = '管技wikiコメント'
       verbose_name_plural = '管技wikiコメント一覧'

   def save(self, *args, **kwargs):
       if not self.pk:
           self.content.save()
       super(ContentComments, self).save(*args, **kwargs)


class ContentsRelation(Contents):
    send_info = models.OneToOneField(
        Contents, on_delete=models.DO_NOTHING, related_name='sended',
        verbose_name='送信ログ', null=True, blank=True)
    menu = models.ForeignKey(Menu, verbose_name='メニュー',
                             on_delete=models.CASCADE,
                             related_name='related_content')
    sort_num = models.IntegerField(
        verbose_name='並び順', default=1, db_index=True)

    def save(self, *args, **kwargs):
        self.sort_num = self.assign_sort_num()
        return super(Contents, self).save(self, *args, **kwargs)

    def replace_sort_num(self, subject: 'ContentsRelation', *args, **kwargs):
        if subject:
            self.sort_num, subject.sort_num = subject.sort_num, self.sort_num
            ContentsRelation.objects.bulk_update(
                [self, subject], fields=['sort_num'])
        else:
            raise ValueError('対象が空です')

    def assign_sort_num(self) -> int:
        content_querySet = ContentsRelation.objects.filter(
            menu=self.menu).all()
        if content_querySet.count() == 0:
            return self.sort_num
        if content_querySet.aggregate(Max('sort_num'))['sort_num__max'] + 1 < self.sort_num:
            return content_querySet.aggregate(Max('sort_num'))['sort_num__max'] + 1
        if content_querySet.filter(sort_num=self.sort_num).count() > 1:
            return content_querySet.aggregate(Max('sort_num'))['sort_num__max'] + 1
        if content_querySet.filter(sort_num=self.sort_num).count() == 1:
            if content_querySet.filter(sort_num=self.sort_num)[0].id != self.id:
                return content_querySet.aggregate(Max('sort_num'))['sort_num__max'] + 1
        return self.sort_num

    def delete(self, *args, **kwargs):
        if self.send_info:
            self.send_info.delete()
        return super().delete(*args, **kwargs)

    class Meta:
        db_table = 'contents_list'
        verbose_name = '管技wikiコンテンツ(一時保存のみ)'
        verbose_name_plural = '管技wikiコンテンツ一覧(一時保存のみ)'

rise_info/infos/models.py
from django.db import models

from addresses.models import Addresses
from eqs.models import Eqtype
from offices.models import Office
from rise_info.baseModels import CommonInfo, BaseAttachment, BaseCommnets
from rise_info.choices import InfoTypeChoices

from datetime import date


class Info(CommonInfo):
    info_type = models.CharField(
        verbose_name='情報種別', max_length=16, choices=InfoTypeChoices.choices,
        default=InfoTypeChoices.TECHINICAL, null=False, blank=False)
    is_rich_text = models.BooleanField(
        verbose_name='リッチテキスト有効', default=False, help_text='内容のリッチテキスト有効/無効')
    managerID = models.CharField(
        verbose_name='管理番号', default="TMC-解析-",
        null=False, blank=False, max_length=32)
    sammary = models.TextField(
        verbose_name='概要', default="", null=False, blank=True, max_length=512)
    is_add_eqtypes = models.BooleanField(verbose_name='装置型式特定', default=True)
    eqtypes = models.ManyToManyField(Eqtype, verbose_name='装置型式', blank=True)
    is_add_offices = models.BooleanField(verbose_name='官署特定', default=True)
    offices = models.ManyToManyField(Office, verbose_name='官署', blank=True)
    addresses = models.ManyToManyField(
        Addresses, verbose_name='受信アドレス', null=True, blank=True,
        related_name='infos')

    def save(self, *args, **kwargs):
        super(Info, self).save(self, *args, **kwargs)

    def delete(self, *args, **kwargs):
        for attachment in self.attachmentfile_set.all():
            attachment.delete()
        return super().delete(*args, **kwargs)

    class Meta:
        db_table = 'infos'
        verbose_name = 'TMC発信情報(全データ)'
        verbose_name_plural = 'TMC発信情報一覧(全データ)'

class AttachmentFile(BaseAttachment):
    info = models.ForeignKey(
        Info, on_delete=models.CASCADE)
    upload_path = 'info'

    class Meta:
        db_table = 'info_attachment'
        verbose_name = 'TMC発信情報添付ファイル'
        verbose_name_plural = 'TMC発信情報添付ファイル一覧'

class InfoComments(BaseCommnets):
    info = models.ForeignKey(
        Info, related_name='infoComment', on_delete=models.CASCADE)
    upload_path = 'info_comments'

    class Meta:
        db_table = 'info_comments'
        verbose_name = 'TMC発信情報コメント'
        verbose_name_plural = 'TMC発信情報コメント一覧'

    def save(self, *args, **kwargs):
        if not self.pk:
            self.info.save()
        super(InfoComments, self).save(*args, **kwargs)


class InfoRelation(Info):
    send_info = models.OneToOneField(
        Info, on_delete=models.DO_NOTHING, related_name='sended',
        verbose_name='送信ログ', null=True, blank=True)

    def delete(self, *args, **kwargs):
        if self.send_info:
            self.send_info.delete()
        return super().delete(*args, **kwargs)

    def setSendInfoAttachment(self):
        if self.send_info:
            attachments = AttachmentFile.objects.filter(info__id = self.send_info.pk)
            for attachment in attachments:
                attachment.delete()
            attachments = AttachmentFile.objects.filter(info__id = self.pk)
            for attachment in attachments:
                attachment.id = None
                attachment.info = self.send_info
                attachment.save()

    class Meta:
        db_table = 'info_list'
        verbose_name = 'TMC発信情報(一時保存)'
        verbose_name_plural = 'TMC発信情報一覧(一時保存)'

rise_info/contents/forms.py
from django import forms

from contents.models import ContentsRelation, AttachmentFile, Menu, ContentComments, Contents
from rise_info.baseForms import MetaCommonInfo, FileSizeValidator


class ContentCommentsForm(forms.ModelForm):
   def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       for _, value in self.fields.items():
           value.widget.attrs['placeholder'] = value.help_text
           value.widget.attrs['class'] = 'form-control'
   content = forms.ModelChoiceField(
       queryset=Contents.objects.all(),
       error_messages={'required': 'contentは必須です', },
   )
   comment_txt = forms.CharField(
       required=True,
       max_length=512,
       error_messages={
           'max_length': 'コメントは512文字以内です',
           'required': 'コメントは必須です',
       },
   )
   file = forms.FileField(
       validators=[FileSizeValidator(val=10, byte_type="mb")],
       required=False,
   )
   class Meta:
       model = ContentComments
       fields = ('content', 'file', 'comment_txt')
       widgets = {
           "comment_txt": forms.Textarea(attrs={
               "class": "form-control",
           }),
           "file": forms.FileInput(attrs={
               "class": "form-control",
           }),
       }


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('menu_title', )


class ContentsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in self.fields.items():
            if not key.startswith('is_'):
                value.widget.attrs['placeholder'] = value.help_text
                if key == 'menu':
                    value.widget.attrs['class'] = 'form-select'
                else:
                    value.widget.attrs['class'] = 'form-control'

    class Meta(MetaCommonInfo):
        model = ContentsRelation
        fields = MetaCommonInfo.fields + ('is_rich_text', 'menu',)
        error_messages = {**MetaCommonInfo.error_messages, **{
            'menu': {
                'required': 'メニューは必須です',
            },
        }}

        widgets = {**MetaCommonInfo.widgets, **{
            'is_rich_text': forms.CheckboxInput(attrs={
                'onclick': 'simplemde = makeSimplemde(this.checked)',
            }),
            'menu': forms.Select(),
            "select_register": forms.TextInput(attrs={
                "type": "hidden",
                "value": "not_registered",
            })
        }}


class AttachmentFileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text
            value.widget.attrs['class'] = 'form-control'

    file = forms.FileField(
        validators=[FileSizeValidator(val=100, byte_type="mb")],
        required=True,
    )

    class Meta(MetaCommonInfo):
        model = AttachmentFile
        fields = '__all__'


FileFormSet = forms.inlineformset_factory(
    ContentsRelation, AttachmentFile, form=AttachmentFileForm, fields='__all__', extra=1,
)

rise_info/contents/templates/contents/baseInfoNewOrEdit.html
{% extends "base.html" %}
{% block extraheader %}
<link rel="stylesheet" href="/static/simplemde/simplemde.min.css">
<link rel="stylesheet" href="/static/fontawesome/css/fontawesome.min.css">
<script src="/static/infos/js/clickCheck.js"></script>

{% endblock %}
{% block main %}
{% block title %}{% endblock %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    <div class="row mt-1">
        <label for="id_title" class="form-label">{{ form.title.label }}</label>
    </div>
    <div class="row mt-1">
        {{ form.title }}
    </div>

    {% block sammary %}{% endblock %}
    <div class="row mt-1">
        <div class="col-2">
            <label for="id_content" class="form-label">
                {{form.content.label}}
            </label>
        </div>
        <div class="col-2">
            <label for="id_is_rich_text" class="form-label">{{form.is_rich_text.label}}</label>
            {{form.is_rich_text}}
        </div>
        {{form.content}}
        <script src="/static/simplemde/simplemde.min.js"></script>
        <script src="/static/infos/js/addSimpleMDE.js"></script>
    </div>
    {% block register %}{% endblock %}
    <div class="row pt-2">
        <div class="col-1 offset-11">
            {% block btn %}{% endblock %}
        </div>
    </div>
</form>
{% endblock %}

{% block add_js %}
<link rel="stylesheet" href="/static/jquery/ui/css/jquery-ui.min.css">
<script src="/static/jquery/jquery-3.6.0.min.js"></script>
<script src="/static/jquery/ui/js/jquery-ui.min.js"></script>
<script src="/static/bootstrap-maxlength/jquery-3.6.0.min.js"></script>
<script src="/static/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script>
    $(function () {
        $("input").on("keydown", function (e) {
            if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
                return false;
            } else {
                return true;
            }
        });
    });

    function setMaxlength(id) {
        $(id).maxlength({
            alwaysShow: true,
            warningClass: "label label-success",
            limitReachedClass: "label label-danger"
        });
    }
    $(document).ready(setMaxlength('#id_title'));
    $(document).ready(setMaxlength('#id_content'));
</script>
{% block add_js2 %}
{% endblock %}
{% endblock %}

rise_info/contents/templates/contents/comment_add_modal.html
<div class="modal fade" id="menuEditModal" tabindex="-1" aria-labelledby="menuEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="menuEditModalLabel">コメントの投稿</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="modalForm" action="/contents/comment_new/" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label" for="id_comment_txt">コメント</label>
                        <textarea class="form-control" name="comment_txt" maxlength="512"
                            id="id_comment_txt"></textarea>
                        <label class="form-label" for="id_file">ファイル</label>
                        <input class="form-control" type="file" name="file" id="id_file">
                        <input type="hidden" name="content" maxlength="24" class="form-control" required=""
                            id="id_content">
                    </div>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button class="btn btn-primary" type="submit" id="modalBTN">投稿</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function showModal(id) {
        var modal = new bootstrap.Modal(document.getElementById('menuEditModal'),);
        var modalTitle = document.getElementById('menuEditModalLabel');
        var modalBTN = document.getElementById('modalBTN');
        var modalForm = document.getElementById('modalForm');
        var input = document.getElementById('id_content');
        input.value = id
        modalForm.action = "/contents/" + id + "/comment/";
        modalTitle.textContent = "コメントの投稿";
        modalBTN.textContent = "投稿";
        modal.show();
    }
</script>

rise_info/contents/templates/contents/contentNewOrEdit.html
{% extends "base.html" %}
{% block extraheader %}
<link rel="stylesheet" href="/static/simplemde/simplemde.min.css">
<link rel="stylesheet" href="/static/fontawesome/css/fontawesome.min.css">
<script src="/static/infos/js/clickCheck.js"></script>

{% endblock %}
{% block main %}
{%if info_id%}
<h1>Wikiの更新</h1>
{%else%}
<h1>Wikiの登録</h1>
{%endif%}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    <div class="row mt-1">
        <label for="id_title" class="form-label fw-bold">{{ form.title.label }}</label>
    </div>
    <div class="row mt-1">
        {{ form.title }}
    </div>
    <div class="row mt-2">
        <div class="col-1">
            <label for="id_menu" class="form-label fw-bold">{{form.menu.label}}</label>
        </div>
        <div class="col-4">
            {{form.menu}}
        </div>
    </div>
    {% include "baseAddAttachment.html" %}
    {% include "base_info_add_new_sammary.html" %}
    <div class="row mt-1">
        <div class="col-2">
            <label for="id_content" class="form-label fw-bold">
                {{form.content.label}}
            </label>
        </div>
        <div class="col-2">
            <label for="id_is_rich_text" class="form-label fw-bold">{{form.is_rich_text.label}}</label>
            {{form.is_rich_text}}
        </div>
        {{form.content}}
        <script src="/static/simplemde/simplemde.min.js"></script>
        <script src="/static/infos/js/addSimpleMDE.js"></script>
    </div>
    {{form.select_register}}
    <div class="row pt-2">
        <div class="col-2 offset-10">
            <button class="btn btn-primary" type="submit" value="post">
                一時保存
            </button>
            <button class="btn btn-primary" onclick='addRegistrationFLG()'>
                {%if info_id%}
                更新
                {%else%}
                登録
                {%endif%}
            </button>
        </div>
    </div>
</form>
{% endblock %}

{% block add_js %}
<link rel="stylesheet" href="/static/jquery/ui/css/jquery-ui.min.css">
<script src="/static/jquery/jquery-3.6.0.min.js"></script>
<script src="/static/jquery/ui/js/jquery-ui.min.js"></script>
<script src="/static/bootstrap-maxlength/jquery-3.6.0.min.js"></script>
<script src="/static/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script src="/static/infos/js/addAttachmentButton.js"></script>
<script>
    <!-- メール送信フラグ追加 -->
    function addRegistrationFLG() {
        var sendMailFLG = document.createElement('input');
        sendMailFLG.type = "hidden";
        sendMailFLG.name = "registration";
        sendMailFLG.value = true;
        document.forms[0].appendChild(sendMailFLG);
    }
</script>
<script>
    <!-- エンターによる送信不可(誤送信対策) -->
    $(function () {
        $("input").on("keydown", function (e) {
            if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
                return false;
            } else {
                return true;
            }
        });
    });
</script>
<script>
    <!-- maxlength設定用 -->
    function setMaxlength(id) {
        $(id).maxlength({
            alwaysShow: true,
            warningClass: "label label-success",
            limitReachedClass: "label label-danger"
        });
    }
    $(document).ready(setMaxlength('#id_title'));
    $(document).ready(setMaxlength('#id_content'));
    $(document).ready(setMaxlength('#id_managerID'));
    $(document).ready(setMaxlength('#id_sammary'));
</script>
{% endblock %}

rise_info/contents/templates/contents/content_detail.html
{% extends "baseDetail.html" %}
{% load bootstrap_icons %}
{% block sammary %}
<ul>
    {% for error in form.comment_txt.errors %}
    <li>
        {{ error }}
    </li>
    {% endfor %}
</ul>
<ul>
    {% for error in form.file.errors %}
    <li>
        {{ error }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

{% block commnets %}

<div class="row pt-2">
    <div class="col-2 offset-10">
        <button type="button" class="btn btn-primary" onclick="showModal({{info.id}})">
            コメント追加
        </button>
    </div>
</div>

{% for comment in info.contentComment.all|dictsortreversed:"created_at"%}
{% include "../baseComment.html" %}
{% endfor %}
{% endblock %}

{% block btn %}
<th><a class="btn btn-primary" href="{% url 'top' %}">戻る</a></th>
{% if auth %}
<th><a class="btn btn-primary" href="{% url 'content_edit' info.id %}" data-bs-toggle="tooltip"
        data-bs-placement="bottom" title="編集">{% bs_icon 'pencil-square' %}</a></th>
{% endif %}

{% include "contents/comment_add_modal.html" %}

{% endblock %}

rise_info/contents/templates/contents/detail.html
{% extends "baseDetail.html" %}
{% block btn %}
<th><a class="btn btn-primary" href="{% url 'top' %}">戻る</a></th>
{% if auth %}
<th><a class="btn btn-primary" href="{% url 'content_edit' info.id %}">編集</a></th>
{% endif %}
{% endblock %}

rise_info/contents/templates/contents/edit.html
{% extends "baseInfoNewOrEdit.html" %}

{% block title %}
<h1>信頼性HPの更新</h1>
{% endblock %}

{% block sammary %}
<div class="row mt-2">
    <div class="col-1">
        <label for="id_menu" class="form-label">{{form.menu.label}}</label>
    </div>
    <div class="col-4">
        {{form.menu}}
    </div>
</div>
{% include "baseAddAttachment.html" %}
{% include "base_info_add_new_sammary.html" %}
{% endblock %}
{% block btn %}
<button class="btn btn-primary mt-2" type="submit" value="post">変更</button>
{% endblock %}

{% block add_js %}
<script src="/static/infos/js/addAttachmentButton.js"></script>
<script>
    $(document).ready(setMaxlength('#id_managerID'));
    $(document).ready(setMaxlength('#id_sammary'));
</script>
{% endblock %}

rise_info/contents/templates/contents/menu_edit_modal.html
<div class="modal fade" id="menuEditModal" tabindex="-1" aria-labelledby="menuEditModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="menuEditModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="modalForm" action="/contents/menu/new/">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label" for="id_menu_title">タイトル</label>
                        <input type="text" name="menu_title" maxlength="24" class="form-control" placeholder="タイトル"
                            required="" id="id_menu_title">
                    </div>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button class="btn btn-primary" type="submit" id="modalBTN">Save changes</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function showModal(menu_id, menu_value) {
        var modal = new bootstrap.Modal(document.getElementById('menuEditModal'),);
        var modalTitle = document.getElementById('menuEditModalLabel');
        var modalBTN = document.getElementById('modalBTN');
        var modalForm = document.getElementById('modalForm');
        var input = document.getElementById('id_menu_title');
        input.value = menu_value
        if (menu_id) {
            modalForm.action = "/contents/menu/new/" + menu_id + "/";
            modalTitle.textContent = "メニューの更新";
            modalBTN.textContent = "更新";
        } else {
            modalForm.action = "/contents/menu/new/";
            modalTitle.textContent = "メニューの追加";
            modalBTN.textContent = "追加";
        }
        modal.show();
    }
</script>

rise_info/contents/templates/contents/new.html
{% extends "baseInfoNewOrEdit.html" %}

{% block title %}
<h1>信頼性HPの登録</h1>
{% endblock %}

{% block sammary %}
<div class="row mt-2">
    <div class="col-1">
        <label for="id_menu" class="form-label">{{form.menu.label}}</label>
    </div>
    <div class="col-4">
        {{form.menu}}
    </div>
</div>
{% include "baseAddAttachment.html" %}
{% include "base_info_add_new_sammary.html" %}
{% endblock %}

{% block btn %}
<button class="btn btn-primary mt-2" type="submit" value="post">登録</button>
{% endblock %}

{% block add_js2 %}
<script src="/static/infos/js/addAttachmentButton.js"></script>
<script>
    $(document).ready(setMaxlength('#id_managerID'));
    $(document).ready(setMaxlength('#id_sammary'));
</script>
{% endblock %}