rise_info/eqs/urls.py
from django.urls import path

from . import views

app_name = 'eqs'

urlpatterns = [
    path('eqtypes/', views.file_upload, name='eqtype'),
    path('eqtypes/download/', views.file_downnload, name='eqtype_download'),
    path("eqtypes/<slug:slug>/del/", views.eqtype_del, name="eqtype_del"),
    path('eqtypes/api/posts/', views.api_posts_get, name='api_posts_get'),
    path('eqtypes/new/', views.eqtype_new, name='eqtype_new'),
    path('eqclass/new/', views.eq_class_new, name='eqclass_new'),
]

rise_info/infos/urls.py
from django.urls import path
from infos import views

urlpatterns = [
    path("", views.InfoList.as_view(), name="info_list"),
    path("new/", views.info_new, name="info_new"),
    path("<int:info_id>/", views.info_detail, name="info_detail"),
    path("<int:info_id>/edit/", views.info_edit, name="info_edit"),
    path("<int:info_id>/del/", views.info_del, name="info_del"),
    path("<int:info_id>/comment/", views.add_comment, name="info_comment"),
    path("<int:info_id>/comment_del/<int:comment_id>/",
         views.del_comment, name="info_del_comment"),
    path("<int:info_id>/send/", views.sendmail, name='info_send'),
    path("export/", views.exportInfo, name='exportInfo'),
]

rise_info/rise_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                # mdeditor
from django.conf.urls import handler400, url    # mdeditor
from django.conf.urls.static import static      # mdeditor
# import debug_toolbar # django toolbar

from rise_info import views

urlpatterns = [
    path("", views.top, name="top"),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("addresses/", include("addresses.urls")),
    path("contents/", include("contents.urls")),
    path("failuer_reports/", include("failuer_reports.urls")),
    path('infos/', include('infos.urls')),
    path('offices/', include('offices.urls')),
    path('eqs/', include('eqs.urls')),
    path('tech_support/', include('tech_supports.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),  # mdeditor
]

handler404 = 'rise_info.views.handler404'
if settings.DEBUG:  # mdeditor
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)    # mdeditor
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.GYOMUSHIEN_URL,
                          document_root=settings.GYOMUSHIEN_ROOT)

# django toolbar
# if settings.DEBUG:
#    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

rise_info/infos/models.py
from django.db import models

from addresses.models import Addresses
from eqs.models import Eqtype
from offices.models import Office
from rise_info.baseModels import CommonInfo, BaseAttachment, BaseCommnets
from rise_info.choices import InfoTypeChoices

from datetime import date


class Info(CommonInfo):
    info_type = models.CharField(
        verbose_name='情報種別', max_length=16, choices=InfoTypeChoices.choices,
        default=InfoTypeChoices.TECHINICAL, null=False, blank=False)
    is_rich_text = models.BooleanField(
        verbose_name='リッチテキスト有効', default=False, help_text='内容のリッチテキスト有効/無効')
    managerID = models.CharField(
        verbose_name='管理番号', default="TMC-解析-",
        null=False, blank=False, max_length=32)
    sammary = models.TextField(
        verbose_name='概要', default="", null=False, blank=True, max_length=512)
    is_add_eqtypes = models.BooleanField(verbose_name='装置型式特定', default=True)
    eqtypes = models.ManyToManyField(Eqtype, verbose_name='装置型式', blank=True)
    is_add_offices = models.BooleanField(verbose_name='官署特定', default=True)
    offices = models.ManyToManyField(Office, verbose_name='官署', blank=True)
    addresses = models.ManyToManyField(
        Addresses, verbose_name='受信アドレス', null=True, blank=True,
        related_name='infos')

    def save(self, *args, **kwargs):
        super(Info, self).save(self, *args, **kwargs)

    def delete(self, *args, **kwargs):
        for attachment in self.attachmentfile_set.all():
            attachment.delete()
        return super().delete(*args, **kwargs)

    class Meta:
        db_table = 'infos'
        verbose_name = 'TMC発信情報(全データ)'
        verbose_name_plural = 'TMC発信情報一覧(全データ)'

class AttachmentFile(BaseAttachment):
    info = models.ForeignKey(
        Info, on_delete=models.CASCADE)
    upload_path = 'info'

    class Meta:
        db_table = 'info_attachment'
        verbose_name = 'TMC発信情報添付ファイル'
        verbose_name_plural = 'TMC発信情報添付ファイル一覧'

class InfoComments(BaseCommnets):
    info = models.ForeignKey(
        Info, related_name='infoComment', on_delete=models.CASCADE)
    upload_path = 'info_comments'

    class Meta:
        db_table = 'info_comments'
        verbose_name = 'TMC発信情報コメント'
        verbose_name_plural = 'TMC発信情報コメント一覧'

    def save(self, *args, **kwargs):
        if not self.pk:
            self.info.save()
        super(InfoComments, self).save(*args, **kwargs)


class InfoRelation(Info):
    send_info = models.OneToOneField(
        Info, on_delete=models.DO_NOTHING, related_name='sended',
        verbose_name='送信ログ', null=True, blank=True)

    def delete(self, *args, **kwargs):
        if self.send_info:
            self.send_info.delete()
        return super().delete(*args, **kwargs)

    def setSendInfoAttachment(self):
        if self.send_info:
            attachments = AttachmentFile.objects.filter(info__id = self.send_info.pk)
            for attachment in attachments:
                attachment.delete()
            attachments = AttachmentFile.objects.filter(info__id = self.pk)
            for attachment in attachments:
                attachment.id = None
                attachment.info = self.send_info
                attachment.save()

    class Meta:
        db_table = 'info_list'
        verbose_name = 'TMC発信情報(一時保存)'
        verbose_name_plural = 'TMC発信情報一覧(一時保存)'

rise_info/contents/forms.py
from django import forms

from contents.models import ContentsRelation, AttachmentFile, Menu, ContentComments, Contents
from rise_info.baseForms import MetaCommonInfo, FileSizeValidator


class ContentCommentsForm(forms.ModelForm):
   def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       for _, value in self.fields.items():
           value.widget.attrs['placeholder'] = value.help_text
           value.widget.attrs['class'] = 'form-control'
   content = forms.ModelChoiceField(
       queryset=Contents.objects.all(),
       error_messages={'required': 'contentは必須です', },
   )
   comment_txt = forms.CharField(
       required=True,
       max_length=512,
       error_messages={
           'max_length': 'コメントは512文字以内です',
           'required': 'コメントは必須です',
       },
   )
   file = forms.FileField(
       validators=[FileSizeValidator(val=10, byte_type="mb")],
       required=False,
   )
   class Meta:
       model = ContentComments
       fields = ('content', 'file', 'comment_txt')
       widgets = {
           "comment_txt": forms.Textarea(attrs={
               "class": "form-control",
           }),
           "file": forms.FileInput(attrs={
               "class": "form-control",
           }),
       }


class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = ('menu_title', )


class ContentsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in self.fields.items():
            if not key.startswith('is_'):
                value.widget.attrs['placeholder'] = value.help_text
                if key == 'menu':
                    value.widget.attrs['class'] = 'form-select'
                else:
                    value.widget.attrs['class'] = 'form-control'

    class Meta(MetaCommonInfo):
        model = ContentsRelation
        fields = MetaCommonInfo.fields + ('is_rich_text', 'menu',)
        error_messages = {**MetaCommonInfo.error_messages, **{
            'menu': {
                'required': 'メニューは必須です',
            },
        }}

        widgets = {**MetaCommonInfo.widgets, **{
            'is_rich_text': forms.CheckboxInput(attrs={
                'onclick': 'simplemde = makeSimplemde(this.checked)',
            }),
            'menu': forms.Select(),
            "select_register": forms.TextInput(attrs={
                "type": "hidden",
                "value": "not_registered",
            })
        }}


class AttachmentFileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text
            value.widget.attrs['class'] = 'form-control'

    file = forms.FileField(
        validators=[FileSizeValidator(val=100, byte_type="mb")],
        required=True,
    )

    class Meta(MetaCommonInfo):
        model = AttachmentFile
        fields = '__all__'


FileFormSet = forms.inlineformset_factory(
    ContentsRelation, AttachmentFile, form=AttachmentFileForm, fields='__all__', extra=1,
)

rise_info/infos/forms.py
from django import forms
from django.urls import reverse_lazy

from infos.models import AttachmentFile, InfoComments, InfoRelation, Info
from rise_info.baseForms import MetaCommonInfo, FileSizeValidator
from eqs.widgets import SuggestWidget
from offices.widgets import OfficeSuggestWidget


class InfoCommentsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text
            value.widget.attrs['class'] = 'form-control'

    info = forms.ModelChoiceField(
        queryset=Info.objects.all(),
        error_messages={'required': 'infoは必須です', },
    )
    comment_txt = forms.CharField(
        required=True,
        max_length=512,
        error_messages={
            'max_length': 'コメントは512文字以内です',
            'required': 'コメントは必須です',
        },
    )
    file = forms.FileField(
        validators=[FileSizeValidator(val=10, byte_type="mb")],
        required=False,
    )

    class Meta:
        model = InfoComments
        fields = ('info', 'file', 'comment_txt')
        widgets = {
            "comment_txt": forms.Textarea(),
            "file": forms.FileInput(),
        }


class InfoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, value in self.fields.items():
            if key != 'offices' and key != 'eqtypes' and not key.startswith('is_'):
                value.widget.attrs['placeholder'] = value.help_text
                if key == 'info_type' or key.startswith('select'):
                    value.widget.attrs['class'] = 'form-select'
                else:
                    value.widget.attrs['class'] = 'form-control'

    class Meta(MetaCommonInfo):
        model = InfoRelation
        fields = MetaCommonInfo.fields + \
            ('info_type', 'managerID', 'sammary', 'is_rich_text',
             'is_add_eqtypes', 'is_add_offices', 'eqtypes', 'offices')
        error_messages = {**MetaCommonInfo.error_messages, **{
            'info_type': {
                'required': '情報種別は必須です',
            },
            'managerID': {
                'required': '管理番号は必須です',
                'max_length': '管理番号は32文字以内です'
            },
            'sammary': {
                'max_length': '概要は512文字以内です',
            },
        }}
        widgets = {**MetaCommonInfo.widgets, **{
            'info_type': forms.widgets.Select(),
            'managerID': forms.TextInput(),
            'sammary': forms.Textarea(attrs={
                "rows": "3",
            }),
            'is_add_offices': forms.CheckboxInput(attrs={
                'onclick': 'clickCheck(this.id, "offices-input", true)',
            }),
            'is_add_eqtypes': forms.CheckboxInput(attrs={
                'onclick': 'clickCheck(this.id, "eqtypes-input", true)',
            }),
            'is_rich_text': forms.CheckboxInput(attrs={
                'onclick': 'simplemde = makeSimplemde(this.checked)',
            }),
            'eqtypes': SuggestWidget(
                attrs={'data-url': reverse_lazy('eqs:api_posts_get')}),
            'offices': OfficeSuggestWidget(attrs={'data-url': reverse_lazy('api_posts_get')}),
            "select_register": forms.TextInput(attrs={
                "type": "hidden",
                "value": "not_registered",
            })
        }}


class AttachmentFileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, value in self.fields.items():
            value.widget.attrs['placeholder'] = value.help_text
            value.widget.attrs['class'] = 'form-control'

    file = forms.FileField(
        validators=[FileSizeValidator(val=100, byte_type="mb")],
        required=True,
    )

    class Meta(MetaCommonInfo):
        model = AttachmentFile
        fields = '__all__'


FileFormSet = forms.inlineformset_factory(
    InfoRelation, AttachmentFile, form=AttachmentFileForm, fields='__all__', extra=1,
)

rise_info/infos/templates/infos/baseInfoAddNewSammary.html
<div class="row mt-2">
    <div class="col-2">
        <label for="id_is_add_eqtypes" class="form-label fw-bold">{{form.is_add_eqtypes.label}}</label>
        {{form.is_add_eqtypes}}
    </div>
    <div class="col-10">
        <label for="id_eqtypes" class="form-label fw-bold">{{form.eqtypes.label}}</label>
        {{form.eqtypes}}
    </div>
</div>
<div class="row mt-2">
    <div class="col-2">
        <label for="id_is_add_offices" class="form-label fw-bold">{{form.is_add_offices.label}}</label>
        {{form.is_add_offices}}
    </div>
    <div class="col-10">
        {{form.offices}}
    </div>
</div>
<div class="row pt-5">
    <div class="col-3">
        <label for="id_info_type" class="form-label fw-bold">{{form.info_type.label}}</label>
        {{form.info_type}}
    </div>
    <div class="col-9">
        <label for="id_managerID" class="form-label fw-bold">{{form.managerID.label}}</label>
        {{form.managerID}}
    </div>
</div>
<div class="row">
    <label for="id_sammary" class="form-label fw-bold">{{form.sammary.label}}</label>
</div>
<div class="row">
    {{form.sammary}}
</div>

rise_info/infos/templates/infos/comment_add_modal.html
<div class="modal fade" id="menuEditModal" tabindex="-1" aria-labelledby="menuEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="menuEditModalLabel">コメントの投稿</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="modalForm" action="/infos/comment_new/" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="form-label fw-bold" for="id_comment_txt">コメント</label>
                        <textarea class="form-control" name="comment_txt" maxlength="512"
                            id="id_comment_txt"></textarea>
                        <label class="form-label fw-bold" for="id_file">ファイル</label>
                        <input class="form-control" type="file" name="file" id="id_file">
                        <input type="hidden" name="info" maxlength="24" class="form-control" required="" id="id_info">
                    </div>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button class="btn btn-primary" type="submit" id="modalBTN">投稿</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function showModal(id) {
        var modal = new bootstrap.Modal(document.getElementById('menuEditModal'),);
        var modalTitle = document.getElementById('menuEditModalLabel');
        var modalBTN = document.getElementById('modalBTN');
        var modalForm = document.getElementById('modalForm');
        var input = document.getElementById('id_info');
        input.value = id
        modalForm.action = "/infos/" + id + "/comment/";
        modalTitle.textContent = "コメントの投稿";
        modalBTN.textContent = "投稿";
        modal.show();
    }
</script>

rise_info/infos/templates/infos/infoNewOrEdit.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% block extraheader %}
<link rel="stylesheet" href="/static/simplemde/simplemde.min.css">
<link rel="stylesheet" href="/static/fontawesome/css/fontawesome.min.css">
<script src="/static/infos/js/clickCheck.js"></script>

{% endblock %}
{% block main %}
{%if info_id%}
<h1>TMC発信情報の更新</h1>
{%else%}
<h1>TMC発信情報の登録</h1>
{%endif%}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    <div class="row mt-1">
        <label for="id_title" class="form-label fw-bold">{{ form.title.label }}</label>
    </div>
    <div class="row mt-1">
        {{ form.title }}
    </div>
    {% include "baseAddAttachment.html" %}
    {% include "infos/baseInfoAddNewSammary.html" %}
    <div class="row mt-1">
        <div class="col-2">
            <label for="id_content" class="form-label fw-bold">
                {{form.content.label}}
            </label>
        </div>
        <div class="col-2">
            <label for="id_is_rich_text" class="form-label fw-bold">{{form.is_rich_text.label}}</label>
            {{form.is_rich_text}}
        </div>
        {{form.content}}
        <script src="/static/simplemde/simplemde.min.js"></script>
        <script src="/static/infos/js/addSimpleMDE.js"></script>
    </div>
    {% include "addAddressesForm.html" %}
    {{form.select_register}}
    <div class="row mt-2">
        <div class="col-2 offset-10">
            <button class="btn btn-primary" type="submit" value="post">
                {%if info_id%}
                更新
                {%else%}
                登録
                {%endif%}
            </button>
            <button class="btn btn-primary" onclick='addSendMailFLG()' data-bs-toggle="tooltip"
                data-bs-placement="bottom" title="メール送信画面へ">
                {% bs_icon 'send' %}
            </button>
        </div>
    </div>

</form>
{% endblock %}

{% block add_js %}
<link rel="stylesheet" href="/static/jquery/ui/css/jquery-ui.min.css">
<script src="/static/jquery/jquery-3.6.0.min.js"></script>
<script src="/static/jquery/ui/js/jquery-ui.min.js"></script>
<script src="/static/bootstrap-maxlength/jquery-3.6.0.min.js"></script>
<script src="/static/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script src="/static/infos/js/addAttachmentButton.js"></script>
<script>
    <!-- メール送信フラグ追加 -->
    function addSendMailFLG() {
        var sendMailFLG = document.createElement('input');
        sendMailFLG.type = "hidden";
        sendMailFLG.name = "sendMailFLG";
        sendMailFLG.value = false;
        document.forms[0].appendChild(sendMailFLG);
    }
</script>
<script>
    <!-- エンターによる送信不可(誤送信対策) -->
    $(function () {
        $("input").on("keydown", function (e) {
            if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
                return false;
            } else {
                return true;
            }
        });
    });
</script>
<script>
    <!-- maxlength設定用 -->
    function setMaxlength(id) {
        $(id).maxlength({
            alwaysShow: true,
            warningClass: "label label-success",
            limitReachedClass: "label label-danger"
        });
    }
    $(document).ready(setMaxlength('#id_title'));
    $(document).ready(setMaxlength('#id_content'));
    $(document).ready(setMaxlength('#id_managerID'));
    $(document).ready(setMaxlength('#id_sammary'));
</script>
{% endblock %}

rise_info/infos/templates/infos/info_list.html
{% extends "base.html" %}
{% load pygmentize %}
{% load custom_filters %}
{% load bootstrap_icons %}
{% block header %}
{% endblock %}

{% block main %}

<div class="welcome row">
    <h1 class="col-10">TMC発信情報一覧</h1>
</div>
<form class="row g-3 my-1" method="get" action="" name="filter_form">
    <div class="col-auto">
        <label for="keyword" class="form-label fw-bold">キーワード:</label>
    </div>
    <div class="col-auto">
        <input class="form-control" type="search" id="keyword" name="keyword" value={{ request.GET|keyword }}>
    </div>
    <div class="col-auto">
        <label for="info_type" class="form-label fw-bold">情報種別:</label>
    </div>
    <div class="col-auto">
        <select class="form-select" type="search" id="info_type" name="info_type">
            <option value="">指定なし</option>
            {% for info_type in info_types %}
            {% if selelcted_info_type == info_type.0 %}
            <option value="{{ info_type.0 }}" selected>
                {% else %}
            <option value="{{ info_type.0 }}">
                {% endif %}
                {{ info_type.1 }}
            </option>
            {%endfor%}
        </select>
    </div>
    <div class="col-auto">
        <label for="eqtype" class="form-label fw-bold">装置型式:</label>
    </div>
    <div class="col-auto">
        <input class="form-control" type="search" id="eqtype" name="eqtype" value={{ request.GET|eqtype }}>
    </div>
    <div class="col-auto">
        <label for="office" class="form-label fw-bold">官署</label>
    </div>
    <div class="col-auto">
        <select class="form-select" type="search" id="office" name="office">
            <option value="">指定なし</option>
            {% for office in offices %}
            {% if selelcted_office == office.pk %}
            <option value="{{ office.pk }}" selected>
                {% else %}
            <option value="{{ office.pk }}">
                {% endif %}
                {{ office.name }}
            </option>
            {%endfor%}
        </select>
    </div>
    {% if auth %}
    <div class="col-auto">
        <label for="is_all" class="form-label fw-bold">非公開情報含む:</label>
    </div>
    <div class="col-auto">
        <input type="checkbox" id="is_all" name="is_all" {{ request.GET|is_all }}>
    </div>
    {%endif%}
    <div class="col-auto">
        <button id="filter" type="submit" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom"
            title="検索">{% bs_icon 'search' %}</button>
    </div>
</form>
<div class="row align-items-start my-1">
    <div class="col-11">
        {% include "pagination.html" %}
    </div>
    {% if auth %}
    <div class="col-1">
        <a class="btn btn-primary mx-2" href="{% url 'info_new' %}" data-bs-toggle="tooltip" data-bs-placement="bottom"
            title="追加">＋</a>
        <a class="btn btn-outline-success mx-2" href="{% url 'exportInfo' %}" data-bs-toggle="tooltip"
            data-bs-placement="bottom" title="Excel一覧出力">{% bs_icon 'file-earmark-excel' %}</a>
    </div>
    {% endif %}

</div>

{% if infos %}
<div class="row border-bottom border-secondary">
    <div class="col-1 h5">情報種別</div>
    <div class="col-2 h5">タイトル</div>
    <div class="col-7 h5">概要</div>
    <div class="col-1 h5">更新日</div>
    <div class="col-1 h5">編集</div>
</div>
{% for info in infos %}
{% if info.send_info %}
<div class="row border-bottom border-secondary py-2">
    <div class="col-1">
        {{ info.send_info.get_info_type_display }}
        </br>
        <span class="badge bg-secondary">公開情報</span>
    </div>
    <div class="col-2"><a href="{% url 'info_detail' info.id %}">{{ info.send_info.title }}</a></div>
    <div class="col-7">{{ info.send_info.sammary }}</div>
    <div class="col-1">{{ info.send_info.updated_at | date:"y/n/j" }}</div>
    {% if auth %}
    <div class="col-1">
        <a class="btn-sm btn-primary" href="{% url 'info_edit' info.send_info.id %}" data-bs-toggle="tooltip"
            data-bs-placement="bottom" title="編集">
            {% bs_icon 'pencil-square' %}
        </a>
        <a class="btn-sm btn-primary" href="{% url 'info_send' info.send_info.id %}" data-bs-toggle="tooltip"
            data-bs-placement="bottom" title="メール送信画面へ">
            {% bs_icon 'send' %}
        </a>
        <a class="btn-sm btn-danger" href="{% url 'info_del' info.id %}" onclick='return confirm("よろしいですか？");'
            data-bs-toggle="tooltip" data-bs-placement="bottom" title="削除">
            {% bs_icon 'trash' %}
        </a>
    </div>
    {% endif %}
</div>
{%else%}
<div class="row border-bottom border-secondary py-2">
    <div class="col-1">
        {{ info.get_info_type_display }}
        </br>
        <span class="badge bg-warning">非公開</span>
    </div>
    <div class="col-2"><a href="{% url 'info_detail' info.id %}">{{ info.title }}</a></div>
    <div class="col-7">{{ info.sammary }}</div>
    <div class="col-1">{{ info.updated_at | date:"y/n/j" }}</div>
    {% if auth %}
    <div class="col-1">
        <a class="btn-sm btn-primary" href="{% url 'info_edit' info.id %}" data-bs-toggle="tooltip"
            data-bs-placement="bottom" title="編集">
            {% bs_icon 'pencil-square' %}
        </a>
        <a class="btn-sm btn-primary" href="{% url 'info_send' info.id %}" data-bs-toggle="tooltip"
            data-bs-placement="bottom" title="メール送信画面へ">
            {% bs_icon 'send' %}
        </a>
        <a class="btn-sm btn-danger" href="{% url 'info_del' info.id %}" onclick='return confirm("よろしいですか？");'
            data-bs-toggle="tooltip" data-bs-placement="bottom" title="削除">
            {% bs_icon 'trash' %}
        </a>
    </div>
    {% endif %}
</div>
{%endif%}
{% endfor %}
{% else %}
<p>信頼性情報はまだ投稿されていません。</p>
{% endif %}
{% endblock %}

rise_info/infos/templates/infos/list.html
{% extends "base.html" %}
{% load pygmentize %}

{% block header %}
<style>
    {% pygments_css %}
</style>
{% endblock %}

{% block main %}

<div class="welcome">
    <h1>信頼性情報一覧</h1>
</div>
{% if auth %}
    <a class="btn btn-primary float-end" href="{% url 'info_new' %}">＋</a>
{% endif %}
{% if infos %}
    <table class="table">
        <thead>
        <tr>
            <th>情報種別</th>
            <th>タイトル</th>
            <th>概要</th>
            <th>投稿日</th>
            <th>編集</th>
        </tr>
        </thead>
        <tbody>
        {% for info in infos %}
        <tr>
            <th>{{ info.get_info_type_display }}</th>
            <th><a href="{% url 'info_detail' info.id %}">{{ info.title }}</a></th>
            <th>{{ info.sammary | linebreaksbr}}</th>
            <th>{{ info.created_at }}</th>
            {% if auth %}
                <th><a class="btn btn-primary" href="{% url 'info_edit' info.id %}">編集</a>
                    <a class="btn btn-danger" href="{% url 'info_del' info.id %}" onclick='return confirm("よろしいですか？");'>削除</a></th>
            {% endif %}
                </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>信頼性情報はまだ投稿されていません。</p>
{% endif %}
{% endblock %}

rise_info/infos/templates/infos/mail_txt.html
{{mail_header | linebreaksbr}}<br>
【{{ info.get_info_type_display }}】{{info.title}}が登録<br>
<br>
概要<br>
{{ info.sammary | linebreaksbr }}<br>
<br>
装置型式<br>
{% for eqtype in info.eqtypes.all %}
{{ eqtype }}<br>
{% endfor %}
<br>
URL<br>
http://cab-rhp.midmlit.local/infos/{{info.id}}/<br>
<br>
{{mail_footer | linebreaksbr}}