rise_info/eqs/urls.py
from django.urls import path

from . import views

app_name = 'eqs'

urlpatterns = [
    path('eqtypes/', views.file_upload, name='eqtype'),
    path('eqtypes/download/', views.file_downnload, name='eqtype_download'),
    path("eqtypes/<slug:slug>/del/", views.eqtype_del, name="eqtype_del"),
    path('eqtypes/api/posts/', views.api_posts_get, name='api_posts_get'),
    path('eqtypes/new/', views.eqtype_new, name='eqtype_new'),
    path('eqclass/new/', views.eq_class_new, name='eqclass_new'),
]

rise_info/failuer_reports/urls.py
from django.urls import path
from failuer_reports import views

urlpatterns = [
    path("", views.FailuerReportRelationList.as_view(),
         name="failuer_report_list"),
    path("new/", views.failuer_report_new, name="failuer_report_new"),
    path("<int:info_id>/", views.failuer_report_detail,
         name="failuer_report_detail"),
    path("<int:info_id>/edit/", views.failuer_report_edit,
         name="failuer_report_edit"),
    path("<int:info_id>/del/", views.failuer_report_del,
         name="failuer_report_del"),
    path("<int:info_id>/send_mail/", views.sendmail,
         name="send_mail"),
]

rise_info/rise_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                # mdeditor
from django.conf.urls import handler400, url    # mdeditor
from django.conf.urls.static import static      # mdeditor
# import debug_toolbar # django toolbar

from rise_info import views

urlpatterns = [
    path("", views.top, name="top"),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("addresses/", include("addresses.urls")),
    path("contents/", include("contents.urls")),
    path("failuer_reports/", include("failuer_reports.urls")),
    path('infos/', include('infos.urls')),
    path('offices/', include('offices.urls')),
    path('eqs/', include('eqs.urls')),
    path('tech_support/', include('tech_supports.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),  # mdeditor
]

handler404 = 'rise_info.views.handler404'
if settings.DEBUG:  # mdeditor
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)    # mdeditor
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.GYOMUSHIEN_URL,
                          document_root=settings.GYOMUSHIEN_ROOT)

# django toolbar
# if settings.DEBUG:
#    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

rise_info/failuer_reports/models.py
from django.db import models
from django_currentuser.db.models import CurrentUserField

from addresses.models import Addresses
from eqs.models import DepartmentForEq
from rise_info.baseModels import CommonInfo, BaseAttachment
from rise_info.choices import ConfirmationTypeChoices, IsConfirmChoices, \
    RegisterStatusChoicesFailuer


class FailuerReport(CommonInfo):
    failuer_date = models.DateField(
        verbose_name='障害発生日', null=True, blank=True,
        help_text="必須"
    )
    failuer_time = models.TimeField(
        verbose_name='障害発生時', null=True, blank=True,
        help_text="必須"
    )
    date_time_confirmation = models.CharField(
        verbose_name='日時確認状態',
        max_length=16,
        choices=ConfirmationTypeChoices.choices,
        help_text='運用者等の管技官以外からの障害検知した場合は当該者と障害発生日時の調整が必要',
        default=ConfirmationTypeChoices.CHECKING_NOW, null=False, blank=False
    )
    failuer_place = models.CharField(
        verbose_name='障害発生場所', default="xx空港",
        null=False, blank=True, max_length=128,
        help_text="必須"
    )
    eq = models.CharField(
        verbose_name="障害装置", null=False,
        blank=True, max_length=128,
        help_text="必須"
    )
    department = models.ManyToManyField(
        DepartmentForEq, verbose_name='影響装置の分類', blank=True,
        help_text='\
ctrlにより複数選択可能。\n\
電源障害時やCas.net障害時等に、影響を受けた分類の全てを選択\n\
本登録により局・本省等の配信先候補を自動判定\n\
必須入力',
    )
    sammary = models.TextField(
        verbose_name='障害概要', default="確認中", null=False, blank=True,
        max_length=1024, help_text="必須項目\n何がどうなったか簡潔に\n例:LOC が●●ALM発生により停止"
    )
    cause = models.TextField(
        verbose_name='障害原因', default="確認中", null=False, blank=True,
        max_length=1024, help_text="必須項目\n現時点で判明している事柄を記載\n例:詳細確認中"
    )
    recovery_date = models.DateField(
        verbose_name='復旧日', null=True, blank=True,
        help_text="復旧日　復旧後記載"
    )
    recovery_time = models.TimeField(
        verbose_name='復旧時', null=True, blank=True,
        help_text="復旧時間　復旧後記載"
    )
    recovery_propects = models.TextField(
        verbose_name='復旧の見通し', default="確認中",
        null=False, blank=True, max_length=1024,
        help_text="必須項目\n分かる範囲で予定等を記載\n例:保守員の派遣を調整中"
    )
    is_flight_impact = models.CharField(
        verbose_name='運航への影響有無', max_length=16,
        choices=IsConfirmChoices.choices,
        default=IsConfirmChoices.CHECKING_NOW,
        null=False, blank=False
    )
    flight_impact = models.TextField(
        verbose_name='運航への影響', default="",
        null=False, blank=True, max_length=512
    )
    notam = models.TextField(
        verbose_name="ノータム",
        null=False, blank=True, max_length=512,
        help_text="ノータム発行があれば記載"
    )
    is_press = models.CharField(
        verbose_name='取材の有無', max_length=16, choices=IsConfirmChoices.choices,
        default=IsConfirmChoices.CHECKING_NOW, null=False, blank=False
    )
    press_contents = models.TextField(
        verbose_name='取材内容', default="取材の内容",
        null=False, blank=True, max_length=1024,
        help_text="\
有の場合はその概要を記入\n\
基本対応\n\
    ①基本的に発生事案については、全ての事項を本省管制技術課で対応\n\
    ②官署への取材等がおこなれる場合を想定し、関係官署の広報担当者に\n\
    　答弁ラインを連絡するとともに、当該官署における航法対応の体制\n\
    　について確認を行う(答弁は当該官署の広報担当者にて実施)\n\
    ③現地官署での取材内容は、本省管制技術課危機管理担当に逐次報告"
    )
    content = models.TextField(
        verbose_name='備考', default="", null=False, blank=True, max_length=4096
    )
    select_register = models.CharField(
        verbose_name='登録状態', max_length=16,
        choices=RegisterStatusChoicesFailuer.choices,
        default=RegisterStatusChoicesFailuer.TEMP, null=False, blank=False
    )

    def save(self, *args, **kwargs):
        super(FailuerReport, self).save(self, *args, **kwargs)

    class Meta:
        db_table = 'failuer_reports'
        verbose_name = '障害通報書(全データ)'
        verbose_name_plural = '障害通報書一覧(全データ)'

class AttachmentFile(BaseAttachment):
    info = models.ForeignKey(FailuerReport, on_delete=models.CASCADE)
    upload_path = 'fail_rep'

    class Meta:
        db_table = 'failuer_report_attachments'
        verbose_name = '障害通報書添付ファイル'
        verbose_name_plural = '障害通報書添付ファイル一覧'


class Circumstances(models.Model):
    info = models.ForeignKey(FailuerReport, on_delete=models.CASCADE)
    date = models.DateField(verbose_name='日付', null=True, blank=True)
    time = models.TimeField(verbose_name='時間', null=True, blank=True)
    event = models.TextField(verbose_name='事案', max_length=256)
    updated_at = models.DateTimeField(
        verbose_name='更新日', auto_now=True, null=False, blank=False)

    class Meta:
        db_table = 'circumstance'
        verbose_name = '障害通報書内事象'
        verbose_name_plural = '障害通報書内事象一覧'


class FailuerReportRelation(FailuerReport):
    send_repo = models.OneToOneField(
        FailuerReport, on_delete=models.DO_NOTHING,
        related_name='sended', verbose_name='送信ログ', null=True, blank=True
    )
    dest_list = models.ManyToManyField(
        Addresses, related_name='failuer_repo_list', null=True, blank=True
    )
    mail_title = models.CharField(
        verbose_name='メール送信件名', max_length=256, null=True, blank=True)
    mail_header = models.TextField(
        verbose_name='メールヘッダー', max_length=512, null=True, blank=True)
    mail_footer = models.TextField(
        verbose_name='メールフッター', max_length=512, null=True, blank=True)

    def set_send_repo(self,select_register):
        if self.send_repo:
            attachments = AttachmentFile.objects.filter(info__id = self.send_repo.pk)
            for attachment in attachments:
                attachment.delete()
            self.send_repo.delete()

        send_repo = self.failuerreport_ptr
        send_repo.id = None
        send_repo.pk = None
        send_repo.select_register = select_register
        send_repo.save()
        self.send_repo = send_repo
        self.save()
        attachments = AttachmentFile.objects.filter(info__id = self.pk)
        for attachment in attachments:
            attachment.id = None
            attachment.info = send_repo
            attachment.save()
        circumstances = Circumstances.objects.filter(info__id = self.pk)
        for circumstance in circumstances:
            circumstance.id = None
            circumstance.info = send_repo
            circumstance.save()


    def delete(self, *args, **kwargs):
        if self.send_repo:
            self.send_repo.delete()
        return super().delete(*args, **kwargs)

    class Meta:
        db_table = 'failuer_repo_list'
        verbose_name = '障害通報書(一時保存)'
        verbose_name_plural = '障害通報書一覧(一時保存)'

rise_info/infos/models.py
from django.db import models

from addresses.models import Addresses
from eqs.models import Eqtype
from offices.models import Office
from rise_info.baseModels import CommonInfo, BaseAttachment, BaseCommnets
from rise_info.choices import InfoTypeChoices

from datetime import date


class Info(CommonInfo):
    info_type = models.CharField(
        verbose_name='情報種別', max_length=16, choices=InfoTypeChoices.choices,
        default=InfoTypeChoices.TECHINICAL, null=False, blank=False)
    is_rich_text = models.BooleanField(
        verbose_name='リッチテキスト有効', default=False, help_text='内容のリッチテキスト有効/無効')
    managerID = models.CharField(
        verbose_name='管理番号', default="TMC-解析-",
        null=False, blank=False, max_length=32)
    sammary = models.TextField(
        verbose_name='概要', default="", null=False, blank=True, max_length=512)
    is_add_eqtypes = models.BooleanField(verbose_name='装置型式特定', default=True)
    eqtypes = models.ManyToManyField(Eqtype, verbose_name='装置型式', blank=True)
    is_add_offices = models.BooleanField(verbose_name='官署特定', default=True)
    offices = models.ManyToManyField(Office, verbose_name='官署', blank=True)
    addresses = models.ManyToManyField(
        Addresses, verbose_name='受信アドレス', null=True, blank=True,
        related_name='infos')

    def save(self, *args, **kwargs):
        super(Info, self).save(self, *args, **kwargs)

    def delete(self, *args, **kwargs):
        for attachment in self.attachmentfile_set.all():
            attachment.delete()
        return super().delete(*args, **kwargs)

    class Meta:
        db_table = 'infos'
        verbose_name = 'TMC発信情報(全データ)'
        verbose_name_plural = 'TMC発信情報一覧(全データ)'

class AttachmentFile(BaseAttachment):
    info = models.ForeignKey(
        Info, on_delete=models.CASCADE)
    upload_path = 'info'

    class Meta:
        db_table = 'info_attachment'
        verbose_name = 'TMC発信情報添付ファイル'
        verbose_name_plural = 'TMC発信情報添付ファイル一覧'

class InfoComments(BaseCommnets):
    info = models.ForeignKey(
        Info, related_name='infoComment', on_delete=models.CASCADE)
    upload_path = 'info_comments'

    class Meta:
        db_table = 'info_comments'
        verbose_name = 'TMC発信情報コメント'
        verbose_name_plural = 'TMC発信情報コメント一覧'

    def save(self, *args, **kwargs):
        if not self.pk:
            self.info.save()
        super(InfoComments, self).save(*args, **kwargs)


class InfoRelation(Info):
    send_info = models.OneToOneField(
        Info, on_delete=models.DO_NOTHING, related_name='sended',
        verbose_name='送信ログ', null=True, blank=True)

    def delete(self, *args, **kwargs):
        if self.send_info:
            self.send_info.delete()
        return super().delete(*args, **kwargs)

    def setSendInfoAttachment(self):
        if self.send_info:
            attachments = AttachmentFile.objects.filter(info__id = self.send_info.pk)
            for attachment in attachments:
                attachment.delete()
            attachments = AttachmentFile.objects.filter(info__id = self.pk)
            for attachment in attachments:
                attachment.id = None
                attachment.info = self.send_info
                attachment.save()

    class Meta:
        db_table = 'info_list'
        verbose_name = 'TMC発信情報(一時保存)'
        verbose_name_plural = 'TMC発信情報一覧(一時保存)'

rise_info/failuer_reports/templates/failuer_reports/circumstances.html
<link rel="stylesheet" href="/static/jquery/ui/css/jquery-ui.min.css">
<script src="/static/jquery/jquery-3.6.0.min.js"></script>
<script src="/static/jquery/ui/js/jquery-ui.min.js"></script>
{{ formset2.management_form }}
<div class="row mt-2 mb-0">
    <div class="col-2">
        <label class="form-label fw-bold">日付</label>
    </div>
    <div class="col-2">
        <label class="form-label fw-bold">時間</label>
    </div>
    <div class="col-7">
        <label class="form-label fw-bold">事象</label>
    </div>
    <div class="col-1">
        <label class="form-label fw-bold">削除</label>
    </div>
</div>
<div id="event-area">
    <hr class="mt-1 mb-1">
    {%for event_form in formset2%}
    <div class="row">
        <div class="col-2">
            {{event_form.date}}
            {{event_form.info}}
            {{event_form.id}}
        </div>
        <div class="col-2">
            {{event_form.time}}
        </div>
        <div class="col-7">
            {{event_form.event}}
        </div>
        <div class="col-1">
            {{event_form.DELETE}}
        </div>
    </div>

    <hr class="mt-1 mb-1">
    {%endfor%}
</div>
<div class="row pt-2">
    <div class="col-1 offset-11">
        <button id="add_event" type="button" class="btn btn-primary">事象の追加</button>
    </div>
</div>

rise_info/failuer_reports/templates/failuer_reports/detail.html
{% extends "baseDetail.html" %}
{% load bootstrap_icons %}
{% block sammary %}
{% if relation_info.mail_title %}
<h4>メール送信件名</h4>
<p>{{relation_info.mail_title}}</p>
{%endif%}
{%if dest_list%}
<h4>送信先</h4>
<table class="table">
    <thead>
        <tr>
            <th>登録官署</th>
            <th>役職</th>
            <th>氏名</th>
        </tr>
    </thead>
    <tbody>
        {% for dest in dest_list %}
        <tr>
            <td>{{dest.created_by}}</td>
            <td>{{dest.position}}</td>
            <td>{{dest.name}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{%endif%}
{{relation_info.mail_header | linebreaksbr}}


<div class="h5 pt-2 mt-2">障害発生日時</div>

<div class="row">
    <div class="col-2">
        {{info.failuer_date}}
    </div>
    <div class="col-4">
        {%if info.date_time_confirmation == "checking_now" %}
        概ね
        {%endif%}
        {{info.failuer_time}}
    </div>
    <div class="col-4">
        {{info.get_date_time_confirmation_display}}
    </div>
</div>
<div class="row">
    <div class="col-1">
        障害発生場所
    </div>
    <div class="col-5">
        {{info.failuer_place}}
    </div>
    <div class="col-1">
        関係官署
    </div>
</div>
<div class="row">
    <div class="col-1">
        障害装置
    </div>
    <div class="col-5">
        {{info.eq}}
    </div>
    <div class="col-1">
        関係装置分類
    </div>
    <div class="col-5">
        {% for department in info.department.all %}
        <span class="badge bg-info text-dark">{{ department }}</span>
        {% endfor %}
    </div>
</div>
<div class="h5 pt-2 mt-2">障害概要</div>
<div class="pb-2 mb-2 border-bottom">
    {{ info.sammary | linebreaksbr }}
</div>
<div class="h5 pt-2 mt-2">障害原因</div>
<div class="pb-2 mb-2 border-bottom">
    {{ info.cause | linebreaksbr }}
</div>
<div class="h5 pt-2 mt-2">復旧の見通し</div>
<div class="pb-2 mb-2 border-bottom">
    {{ info.recovery_propects | linebreaksbr }}
</div>
<div class="pb-2 mb-2 border-bottom">
    <p>{{ info.operatinal_impact }}</p>
</div>
<div class="row pt-2 mt-2">
    <h5 class="col-2">運航への影響：</h5>
    <div class="col-auto">{{ info.get_is_flight_impact_display }}</div>
</div>
<div class="pb-2 mb-2 border-bottom">
    <p>{{ info.flight_impact }}</p>
</div>
<div class="row pt-2 mt-2">
    <h5 class="col-2">ノータム：</h5>
    <div class="col-auto">{{ info.notam | linebreaksbr }}</div>
</div>
<div class="row pt-2 mt-2">
    <h5 class="col-1">取材の有無：</h5>
    <div class="col-auto">{{ info.get_is_press_display }}</div>
</div>
<div class="pb-2 mb-2 border-bottom">
    <p>{{ info.press_contents | linebreaksbr }}</p>
</div>

<div class="h5 pt-2 mt-2">経緯</div>
<div class="pb-2 mb-2 border-bottom">
    {%for event in events%}
    {%if info.updated_at >= event.updated_at%}
    <div class="row">
        <div class="col-2">
            {% ifchanged  event.date %}
            {%if event.date%}{{event.date}}{%endif%}
            {% endifchanged %}
        </div>
        <div class="col-1">
            {%if event.time%}{{event.time}}{%endif%}
        </div>
        <div class="col-9">
            {{event.event|linebreaksbr}}
        </div>
    </div>
    {%endif%}
    {%endfor%}
</div>
{% if relation_info.mail_footer %}
{{relation_info.mail_footer | linebreaksbr}}
{%endif%}
{% endblock %}

{% block btn %}
<th><a class="btn btn-primary" href="{% url 'failuer_report_list' %}">
        戻る
    </a></th>
{% if user == info.created_by %}
<th><a class="btn btn-primary" href="{% url 'send_mail' info.id %}" data-bs-toggle="tooltip" data-bs-placement="bottom"
        title="メール送信">
        {% bs_icon 'send' %}
    </a></th>
<th><a class="btn btn-primary" href="{% url 'failuer_report_edit' info.id %}" data-bs-toggle="tooltip"
        data-bs-placement="bottom" title="編集">
        {% bs_icon 'pencil-square' %}
    </a></th>
<th><a class="btn btn-danger" href="{% url 'failuer_report_del' info.id %}" onclick='return confirm("よろしいですか？");'
        data-bs-toggle="tooltip" data-bs-placement="bottom" title="削除">
        {% bs_icon 'trash' %}
    </a></th>
{% endif %}

{% endblock %}

rise_info/failuer_reports/templates/failuer_reports/failuerReportsNewOrEdit.html
{% extends "base.html" %}
{% load bootstrap_icons %}
{% block extraheader %}
<link rel="stylesheet" href="/static/simplemde/simplemde.min.css">
<link rel="stylesheet" href="/static/fontawesome/css/fontawesome.min.css">
<script src="/static/infos/js/clickCheck.js"></script>

{% endblock %}
{% block main %}
{%if info_id%}
<h1>障害通報の更新</h1>
{%else%}
<h1>障害通報の登録</h1>
{%endif%}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    <div class="row mt-1">
        <label for="id_title" class="form-label fw-bold">{{ form.title.label }}</label>
    </div>
    <div class="row mt-1">
        {{ form.title }}
    </div>
    {% include "failuer_reports/failureSammary.html" %}
    {% include "failuer_reports/circumstances.html" %}
    {% include "baseAddAttachment.html" %}
    <div class="row mt-1">
        <div class="col-2">
            <label for="id_content" class="form-label fw-bold">
                {{form.content.label}}
            </label>
        </div>
        <div class="col-2">
            <label for="id_is_rich_text" class="form-label fw-bold">{{form.is_rich_text.label}}</label>
            {{form.is_rich_text}}
        </div>
        {{form.content}}
        <script src="/static/simplemde/simplemde.min.js"></script>
        <script src="/static/infos/js/addSimpleMDE.js"></script>
    </div>
    <div class="row pt-2">
        <div class="col-1 offset-11">
            <button class="btn btn-primary" type="submit" value="post">
                {%if info_id%}
                更新
                {%else%}
                登録
                {%endif%}
            </button>
            <button class="btn btn-primary" onclick='addSendMailFLG()' data-bs-toggle="tooltip"
                data-bs-placement="bottom" title="メール送信">
                {% bs_icon 'send' %}
            </button>
        </div>
    </div>

</form>
{% endblock %}

{% block add_js %}
<link rel="stylesheet" href="/static/jquery/ui/css/jquery-ui.min.css">
<script src="/static/jquery/jquery-3.6.0.min.js"></script>
<script src="/static/jquery/ui/js/jquery-ui.min.js"></script>
<script src="/static/bootstrap-maxlength/jquery-3.6.0.min.js"></script>
<script src="/static/bootstrap-maxlength/bootstrap-maxlength.min.js"></script>
<script src="/static/infos/js/clickCheck.js"></script>
<script src="/static/infos/js/addAttachmentButton.js"></script>
<script>
    <!-- エンターによる送信不可(誤送信対策) -->
    $(function () {
        $("input").on("keydown", function (e) {
            if ((e.which && e.which === 13) || (e.keyCode && e.keyCode === 13)) {
                return false;
            } else {
                return true;
            }
        });
    });
</script>
<script>
    <!-- maxlength設定用 -->
    function setMaxlength(id) {
        $(id).maxlength({
            alwaysShow: true,
            warningClass: "label label-success",
            limitReachedClass: "label label-danger"
        });
    }
    $(document).ready(setMaxlength('#id_title'));
    $(document).ready(setMaxlength('#id_content'));
    $(document).ready(setMaxlength('#id_sammary'));
    $(document).ready(setMaxlength('#id_operatinal_impact'));
    $(document).ready(setMaxlength('#id_flight_impact'));
    $(document).ready(setMaxlength('#id_failuer_place'));
    $(document).ready(setMaxlength('#id_eq'));
    $(document).ready(setMaxlength('#id_recovery_propects'));
    $(document).ready(setMaxlength('#id_press_contents'));
    $(document).ready(setMaxlength('#id_notam'));
    $(document).ready(setMaxlength('#id_circumstances_set-0-event'));
</script>
<script>
    <!-- メール送信フラグ追加 -->
    function addSendMailFLG() {
        var sendMailFLG = document.createElement('input');
        sendMailFLG.type = "hidden";
        sendMailFLG.name = "sendMailFLG";
        sendMailFLG.value = false;
        document.forms[0].appendChild(sendMailFLG);
    }
</script>
{% endblock %}

rise_info/failuer_reports/templates/failuer_reports/failureSammary.html
<div class="row mt-2 mb-0">
    <div class="col-2">
        <label for="id_failuer_date" class="form-label fw-bold">{{form.failuer_date.label}}</label>
    </div>
    <div class="col-2">
        <label for="id_failuer_time" class="form-label fw-bold">{{form.failuer_time.label}}</label>
    </div>
    <div class="col-3">
        <label for="id_date_time_confirmation" class="form-label fw-bold">{{form.date_time_confirmation.label}}</label>
    </div>
    <div class="col-5">
        <label for="id_failuer_place" class="form-label fw-bold">{{form.failuer_place.label}}</label>
    </div>
</div>
<div class="row mt-0">
    <div class="col-2">
        {{form.failuer_date}}
    </div>
    <div class="col-2">
        {{form.failuer_time}}
    </div>
    <div class="col-3">
        {{form.date_time_confirmation}}
    </div>
    <div class="col-5">
        {{form.failuer_place}}
    </div>
</div>
<div class="row form-text">
    <div class="col-12">
        {{form.date_time_confirmation.help_text|safe}}
    </div>
</div>
<div class="row mt-2 mb-0">
    <div class="col-1">
        <label for="id_eq" class="form-label fw-bold">{{form.eq.label}}</label>
    </div>
    <div class="col-4">
        {{form.eq}}
    </div>
    <div class="col-1">
        <label for="id_department" class="form-label fw-bold">{{form.department.label}}</label>
    </div>
    <div class="col-3">
        {{form.department}}
    </div>
    <div class="col-3 form-text">
        {{form.department.help_text | safe | linebreaksbr}}
    </div>
</div>

<div class="row mt-1">
    <label for="id_sammary" class="form-label fw-bold">{{form.sammary.label}}</label>
</div>
<div class="row mt-0">
    {{form.sammary}}
</div>
<div class="row mt-1">
    <label for="id_cause" class="form-label fw-bold">{{form.cause.label}}</label>
</div>
<div class="row mt-0">
    {{form.cause}}
</div>
<div class="row mt-2 mb-0">
    <div class="col-2">
        <label for="id_recovery_date" class="form-label fw-bold">{{form.recovery_date.label}}</label>
    </div>
    <div class="col-2">
        <label for="id_recovery_time" class="form-label fw-bold">{{form.recovery_time.label}}</label>
    </div>
</div>
<div class="row mt-0">
    <div class="col-2">
        {{form.recovery_date}}
    </div>
    <div class="col-2">
        {{form.recovery_time}}
    </div>
</div>
<div class="row mt-1">
    <label for="id_recovery_propects" class="form-label fw-bold">{{form.recovery_propects.label}}</label>
</div>
<div class="row mt-0">
    {{form.recovery_propects}}
</div>
<div class="row mt-1">
    <div class="col-1">
        <label for="id_is_flight_impact" class="form-label fw-bold">{{form.is_flight_impact.label}}</label>
    </div>
    <div class="col-2">
        {{form.is_flight_impact}}
    </div>
    <div class="col-9">
        {{form.flight_impact}}
    </div>
</div>
<div class="row mt-1">
    <div class="col-1">
        <label for="id_notam" class="form-label fw-bold">{{form.notam.label}}</label>
    </div>
    <div class="col-11">
        {{form.notam}}
    </div>

</div>
<div class="row mt-1">
    <div class="col-1">
        <label for="id_is_press" class="form-label fw-bold">{{form.is_press.label}}</label>
    </div>
    <div class="col-2">
        {{form.is_press}}
    </div>
    <div class="col-9">
        {{form.press_contents}}
    </div>
</div>
{{form.select_register}}