rise_info/eqs/urls.py
from django.urls import path

from . import views

app_name = 'eqs'

urlpatterns = [
    path('eqtypes/', views.file_upload, name='eqtype'),
    path('eqtypes/download/', views.file_downnload, name='eqtype_download'),
    path("eqtypes/<slug:slug>/del/", views.eqtype_del, name="eqtype_del"),
    path('eqtypes/api/posts/', views.api_posts_get, name='api_posts_get'),
    path('eqtypes/new/', views.eqtype_new, name='eqtype_new'),
    path('eqclass/new/', views.eq_class_new, name='eqclass_new'),
]

rise_info/rise_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                # mdeditor
from django.conf.urls import handler400, url    # mdeditor
from django.conf.urls.static import static      # mdeditor
# import debug_toolbar # django toolbar

from rise_info import views

urlpatterns = [
    path("", views.top, name="top"),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("addresses/", include("addresses.urls")),
    path("contents/", include("contents.urls")),
    path("failuer_reports/", include("failuer_reports.urls")),
    path('infos/', include('infos.urls')),
    path('offices/', include('offices.urls')),
    path('eqs/', include('eqs.urls')),
    path('tech_support/', include('tech_supports.urls')),
    url(r'mdeditor/', include('mdeditor.urls')),  # mdeditor
]

handler404 = 'rise_info.views.handler404'
if settings.DEBUG:  # mdeditor
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)    # mdeditor
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.GYOMUSHIEN_URL,
                          document_root=settings.GYOMUSHIEN_ROOT)

# django toolbar
# if settings.DEBUG:
#    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

rise_info/eqs/models.py
from django.db import models
from django.db.models import Max
from django.urls import reverse
from django.utils.text import slugify

import csv
import shutil
import pytz
from datetime import datetime as dt

from rise_info.baseModels import BaseManager
from histories.models import getLastUpdateAt, setLastUpdateAt


def isImportRow(row) -> bool:
    sysupdtime = dt.strptime(row['DATASAKUSEI_DATE'], '%Y/%m/%d %H:%M')
    sysupdtime = sysupdtime.replace(tzinfo=pytz.timezone('Asia/Tokyo'))
    lastUpdateAt = getLastUpdateAt('eqtype').replace(
        tzinfo=pytz.timezone('Asia/Tokyo'))
    return sysupdtime > lastUpdateAt


def eqtypes_csv_import():
    with open('uploads/documents/EQTypes.csv', 'rt', encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        eqtypes = [row for row in reader]
        eqtype_create_object = []
        for row in eqtypes:
            sysupdtime = dt.strptime(row['DATASAKUSEI_DATE'], '%Y/%m/%d %H:%M')
            if isImportRow(row):
                if not Eqtype.objects.filter(id=row['SOCHIKATA']).exists():
                    eqtype_create_object.append(Eqtype(
                        id=row['SOCHIKATA'],
                        slug=slugify(row['SOCHIKATA']),
                        create_at=sysupdtime.replace(
                            tzinfo=pytz.timezone('Asia/Tokyo'))
                    ))

        Eqtype.objects.bulk_create(eqtype_create_object)
        last_update_at = Eqtype.objects.all().aggregate(
            Max('create_at'))['create_at__max']
        setLastUpdateAt('eqtype', last_update_at.replace(
            tzinfo=pytz.timezone('Asia/Tokyo')))
        shutil.copy2('uploads/documents/EQTypes.csv',
                     'uploads/documents/EQTypes_tmp.csv')


class DepartmentForEq(models.Model):
    objects = BaseManager()
    id = models.SlugField(verbose_name='担当部署略号',
                          primary_key=True, max_length=8)
    name = models.CharField(verbose_name="担当部署名", max_length=24)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '装置担当部署'
        verbose_name_plural = '装置担当部署一覧'

class EQ_class(models.Model):
    objects = BaseManager()
    id = models.CharField(verbose_name='装置分類', max_length=16,
                          primary_key=True, editable=False)
    department = models.ManyToManyField(DepartmentForEq,
                                        verbose_name="装置担当部署", related_name="eq_class",
                                        null=True, blank=True)
    memo = models.TextField(
        verbose_name='備考', max_length=256, null=True, blank=True)

    def __str__(self) -> str:
        return self.id

    class Meta:
        db_table = 'eqclass'
        verbose_name = '装置分類'
        verbose_name_plural = '装置分類一覧'


class Eqtype(models.Model):
    objects = BaseManager()
    id = models.CharField(verbose_name='装置型式',
                          primary_key=True, editable=False, max_length=24)
    slug = models.SlugField(verbose_name='装置型式(URL)',
                            unique=True, null=False, editable=False,
                            max_length=24)
    eq_class = models.ForeignKey(
        EQ_class, verbose_name='装置分類', null=True, blank=True,
        related_name='eqtype', on_delete=models.CASCADE)
    create_at = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)

    def __str__(self):
        return self.id

    def get_absolute_url(self):
        return reverse('eqtype_del', kwargs={'slug': self.slug})

    class Meta:
        db_table = 'eqtypes'
        verbose_name = '装置型式'
        verbose_name_plural = '装置型式一覧'

rise_info/infos/models.py
from django.db import models

from addresses.models import Addresses
from eqs.models import Eqtype
from offices.models import Office
from rise_info.baseModels import CommonInfo, BaseAttachment, BaseCommnets
from rise_info.choices import InfoTypeChoices

from datetime import date


class Info(CommonInfo):
    info_type = models.CharField(
        verbose_name='情報種別', max_length=16, choices=InfoTypeChoices.choices,
        default=InfoTypeChoices.TECHINICAL, null=False, blank=False)
    is_rich_text = models.BooleanField(
        verbose_name='リッチテキスト有効', default=False, help_text='内容のリッチテキスト有効/無効')
    managerID = models.CharField(
        verbose_name='管理番号', default="TMC-解析-",
        null=False, blank=False, max_length=32)
    sammary = models.TextField(
        verbose_name='概要', default="", null=False, blank=True, max_length=512)
    is_add_eqtypes = models.BooleanField(verbose_name='装置型式特定', default=True)
    eqtypes = models.ManyToManyField(Eqtype, verbose_name='装置型式', blank=True)
    is_add_offices = models.BooleanField(verbose_name='官署特定', default=True)
    offices = models.ManyToManyField(Office, verbose_name='官署', blank=True)
    addresses = models.ManyToManyField(
        Addresses, verbose_name='受信アドレス', null=True, blank=True,
        related_name='infos')

    def save(self, *args, **kwargs):
        super(Info, self).save(self, *args, **kwargs)

    def delete(self, *args, **kwargs):
        for attachment in self.attachmentfile_set.all():
            attachment.delete()
        return super().delete(*args, **kwargs)

    class Meta:
        db_table = 'infos'
        verbose_name = 'TMC発信情報(全データ)'
        verbose_name_plural = 'TMC発信情報一覧(全データ)'

class AttachmentFile(BaseAttachment):
    info = models.ForeignKey(
        Info, on_delete=models.CASCADE)
    upload_path = 'info'

    class Meta:
        db_table = 'info_attachment'
        verbose_name = 'TMC発信情報添付ファイル'
        verbose_name_plural = 'TMC発信情報添付ファイル一覧'

class InfoComments(BaseCommnets):
    info = models.ForeignKey(
        Info, related_name='infoComment', on_delete=models.CASCADE)
    upload_path = 'info_comments'

    class Meta:
        db_table = 'info_comments'
        verbose_name = 'TMC発信情報コメント'
        verbose_name_plural = 'TMC発信情報コメント一覧'

    def save(self, *args, **kwargs):
        if not self.pk:
            self.info.save()
        super(InfoComments, self).save(*args, **kwargs)


class InfoRelation(Info):
    send_info = models.OneToOneField(
        Info, on_delete=models.DO_NOTHING, related_name='sended',
        verbose_name='送信ログ', null=True, blank=True)

    def delete(self, *args, **kwargs):
        if self.send_info:
            self.send_info.delete()
        return super().delete(*args, **kwargs)

    def setSendInfoAttachment(self):
        if self.send_info:
            attachments = AttachmentFile.objects.filter(info__id = self.send_info.pk)
            for attachment in attachments:
                attachment.delete()
            attachments = AttachmentFile.objects.filter(info__id = self.pk)
            for attachment in attachments:
                attachment.id = None
                attachment.info = self.send_info
                attachment.save()

    class Meta:
        db_table = 'info_list'
        verbose_name = 'TMC発信情報(一時保存)'
        verbose_name_plural = 'TMC発信情報一覧(一時保存)'

rise_info/templates/addAddressesForm.html
<div class="row mt-2">
    <h4>コメント追加時の配信先</h4>
</div>
<div class="row border-bottom border-secondary">
    <div class="col-2 h5">登録官署</div>
    <div class="col-3 h5">役職</div>
    <div class="col-2 h5">氏名</div>
    <div class="col-3 h5">アドレス</div>
    <div class="col-2">
        <div class="row">
            <div class="h5 col-auto">配信有無</div>
            <div class="col-auto">
                <input class="form-check-input" id="checkAll" type="checkbox" name="lang" value="checkall">全て選択</label>
            </div>
        </div>
    </div>
</div>
{%for address in addresses%}
<div class="row border-bottom border-secondary">
    <div class="col-2">{{address.created_by.last_name}}</div>
    <div class="col-3">{{address.position}}</div>
    <div class="col-2">{{address.name}}</div>
    <div class="col-3">{{address.mail}}</div>
    <div class="col-2">
        <div class="form-check">
            <input class="form-check-input checks" type="checkbox" value="{{address.id}}" id="add_addresses"
                name="add_addresses[]" {%if tech_supo%} {%if info in address.tech_support.all%} checked
                {%endif%}{%else%} {%if info in address.infos.all%} checked {%endif%} {%endif%}>
        </div>
    </div>
</div>
<script>
    let checkAll = document.getElementById("checkAll");
    //「全て選択」以外のチェックボックス
    let el = document.getElementsByClassName("checks");
    //全てのチェックボックスをON/OFFする
    const funcCheckAll = (bool) => {
        for (let i = 0; i < el.length; i++) {
            el[i].checked = bool;
        }
    }

    //「checks」のclassを持つ要素のチェック状態で「全て選択」のチェック状態をON/OFFする
    const funcCheck = () => {
        let count = 0;
        for (let i = 0; i < el.length; i++) {
            if (el[i].checked) {
                count += 1;
            }
        }

        if (el.length === count) {
            checkAll.checked = true;
        } else {
            checkAll.checked = false;
        }
    };

    //「全て選択」のチェックボックスをクリックした時
    checkAll.addEventListener("click", () => {
        funcCheckAll(checkAll.checked);
    }, false);

    //「全て選択」以外のチェックボックスをクリックした時
    for (let i = 0; i < el.length; i++) {
        el[i].addEventListener("click", funcCheck, false);
    }

</script>
{%endfor%}

rise_info/templates/base.html
{% load static %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>信頼性ＨＰ</title>
    <link href="/static/bootstrap5/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/menu/css/dropdown-submenu.css" rel="stylesheet">
    <script src="/static/bootstrap5/js/bootstrap.bundle.min.js"></script>
    {% block extraheader %}{% endblock %}
</head>

<body>
    <div class="container-fluid">
        <div class='fixed-top'>
            <nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
                <div class="d-flex container-fluid justify-content-between">
                    <a href="/" class="navbar-brand">信頼性ＨＰ</a>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'info_list' %}">TMC発信情報</a> </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'support_list' %}">官署発信機能</a> </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                管制技術Wiki
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% for menu in menus %}
                                <li><a class="dropdown-item" href="#">
                                        {{ menu.menu_title }} &raquo;
                                    </a>
                                    <ul class="dropdown-menu dropdown-submenu">
                                        {% for content in menu.related_content.all|dictsort:"sort_num" %}
                                        {%if content.send_info %}
                                        <li>
                                            <a class="dropdown-item" href="{% url 'content_detail' content.send_info.id %}">
                                                {{ content.send_info }}</a>
                                        </li>
                                        {%endif%}
                                        {% endfor %}
                                    </ul>
                                </li>
                                {% endfor %}
                                {% if auth %}
                                <li><a class="dropdown-item" href="{% url 'menu_list' %}">メニュー管理</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'failuer_report_list' %}">障害通報</a> </li>
                        <li class="nav-item"><a class="nav-link" href="/gyoumushien/index.html" target="new">業務支援</a> </li>
                        {% if auth %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'office' %}">官署</a> </li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'eqs:eqtype' %}">装置型式</a> </li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav mr-md-2">
                        <li class="nav-item dropdown">
                            {% if user %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                <img src="/media/user.png" class="avatar" width="30px" height="30px" />{{ user.last_name }}
                            </a>
                            {% else %}
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                ユーザ管理
                            </a>
                            {% endif %}
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'logout' %}">ログアウト</a></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">パスワード変更</a></li>
                                <li><a class="dropdown-item" href="{% url 'address_list' %}">配信先管理</a></li>
                                <li><a class="dropdown-item" href="{% url 'userconfig' %}">メール設定</a></li>
                                {% if user.username == 'root' %}
                                <li><a class="dropdown-item" href="{% url 'account_list' %}">ユーザ管理</a></li>
                                {% endif %}
                                {% else %}
                                <li><a class="dropdown-item" href="{% url 'login' %}">ログイン</a></li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="row"><br/><br/><br/></div>
    <main>
        <div class="container-fluid">
            {% for message in messages %}
            <div {% if message.tags %}class="{{ message.tags }}" {% endif %}>
                {{ message | linebreaksbr }}
            </div>
            {% endfor %}
            {% if form.errors %}
            <div class="alert alert-warning">
                {{ form.errors }}
            </div>
            {%endif%}
            {%if formset.erros%}
            {%for error in formset.errors%}
            {%if error%}<div class="alert alert-warning">{{error}}</div>{%endif%}
            {%endfor%}
            {%endif%}
            {%if formset2%}
            {%for error in formset2.errors%}
            {%if error%}<div class="alert alert-warning">{{error}}</div>{%endif%}
            {%endfor%}
            {%endif%}
            {% block main %}{% endblock %}
        </div>
    </main>
    </div>
</body>
<script src="/static/jquery/jquery-3.6.0.min.js"></script>
{% block add_js %}{% endblock %}

</html>

rise_info/templates/baseAddAttachment.html
<h2>添付ファイル</h2>
{{ formset.management_form }}
<div id="file-area">
    {% for file_form in formset %}
    <div class="row pb-2">
        <div class="col-5">
            <input class="form-control" type="file" name="attachmentfile_set-{{ forloop.counter0 }}-file"
                id="id_attachmentfile_set-{{ forloop.counter0 }}-file"
                onchange="change('id_btn-{{ forloop.counter0 }}')">
            {{ file_form.info }}
            {{ file_form.id }}
        </div>
        {% if file_form.id.value %}
        <div class="col-5">
            <a href="/media/{{ file_form.file.value }}">{{ file_form.filename.value }}</a>
            <input type="text" id="id_file-{{ forloop.counter0 }}-img_link"
                value='&lt;img src="/media/{{ file_form.file.value }}" width="100%" /&gt;' hidden disabled>
            {% if '.jpg' in file_form.filename.value or '.jpeg' in file_form.filename.value %}
            <button id="id_btn-{{ forloop.counter0 }}" type="button" class="btn btn-primary"
                onclick="copy('id_file-{{ forloop.counter0 }}-img_link')">画像ファイルパスコピー</button>
            {%endif%}
            {% if '.gif' in file_form.filename.value or '.png' in file_form.filename.value %}
            <button id="id_btn-{{ forloop.counter0 }}" type="button" class="btn btn-primary"
                onclick="copy('id_file-{{ forloop.counter0 }}-img_link')">画像ファイルパスコピー</button>
            {%endif%}
        </div>
        <div class="col-2">
            <input class="form-check-input" type="checkbox" name="attachmentfile_set-{{ forloop.counter0 }}-DELETE"
                id="id_attachmentfile_set-{{ forloop.counter0 }}-DELETE">
            <label class="form-check-label" for="id_attachmentfile_set-{{ forloop.counter0 }}-DELETE">削除</label>
        </div>
        {% endif %}
    </div>
    {% endfor %}
</div>
<div class="row pt-2">
    <div class="col-2 offset-4">
        <button id="add" type="button" class="btn btn-primary">ファイルの追加</button>
    </div>
</div>

rise_info/templates/baseAddAttachment_js.html
<script>
$(function(){
    var totalManageElement = $('input#id_{{ model_name }}_set-TOTAL_FORMS');
    var currentFileCount = parseInt(totalManageElement.val());
    $('button#add').on('click', function(){
        var rowElement = $('<div>', {
            class: 'row pb-2',
        });
        var col5_1Element =$('<div>', {
            class: 'col-5',
        }); 
        var col5_2Element =$('<div>', {
            class: 'col-5',
        }); 
        var col2Element =$('<div>', {
            class: 'col-2',
        });
        var fileElement = $('<input>', {
            class: 'form-control',
            type: 'file',
            name: '{{ model_name }}_set-' + currentFileCount + '-file',
            id: 'id_{{ model_name }}_set-' + currentFileCount + '-file',
        });
        var delElement = $('<input>', {
            class: 'form-check-input',
            type: 'checkbox',
            name: '{{ model_name }}_set-' + currentFileCount + '-DELETE',
            id: 'id_{{ model_name }}_set-' + currentFileCount + '-DELETE',
        });
        var delLabelElement = $('<label>', {
            class: 'form-check-label',
            for: 'id_{{ model_name }}_set-' + currentFileCount + '-DELETE',
        });
        delLabelElement.text("削除")
        col5_1Element.append(fileElement);
        col2Element.append(delElement);
        col2Element.append(delLabelElement);
        rowElement.append(col5_1Element);
        rowElement.append(col2Element);
        $('div#file-area').append(rowElement);
        currentFileCount += 1;
        totalManageElement.attr('value', currentFileCount);
    });
});
</script>

rise_info/templates/baseComment.html
{% load bootstrap_icons %}
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="card-subtitle">{{ comment.comment_txt | linebreaksbr}}</div>
        </div>
        <div class="row">
            <div class="card-subtitle">
                <p><a href="/media/{{ comment.file }}">{{ comment.filename }}</a></p>
            </div>
        </div>
        <div class="row">
            <div class="col-5"></div>
            <div class="col-3">投稿者：{{ comment.created_by.last_name }}</div>
            <div class="col-3">投稿日時{{ comment.created_at }}</div>
            {% if user == comment.created_by %}
            <div class="col-1">
                {% if is_content %}
                <th><a class="btn btn-danger" href="{% url 'content_del_comment' info.id comment.id %}"
                        onclick='return confirm("よろしいですか？");' data-bs-toggle="tooltip" data-bs-placement="bottom"
                        title="削除">
                        {% bs_icon 'trash' %}
                    </a></th>
                {% elif is_support %}
                <th><a class="btn btn-danger" href="{% url 'support_del_comment' info.id comment.id %}"
                        onclick='return confirm("よろしいですか？");' data-bs-toggle="tooltip" data-bs-placement="bottom"
                        title="削除">
                        {% bs_icon 'trash' %}
                    </a></th>
                {% else %}
                <th><a class="btn btn-danger" href="{% url 'info_del_comment' info.id comment.id %}"
                        onclick='return confirm("よろしいですか？");' data-bs-toggle="tooltip" data-bs-placement="bottom"
                        title="削除">
                        {% bs_icon 'trash' %}
                    </a></th>
                {% endif %}
            </div>
            {% endif %}
        </div>

    </div>
</div>

rise_info/templates/base_failure_add_new_sammary.html
<div class="row mt-2 mb-0">
    <div class="col-2">
        <label for="id_failuer_date" class="form-label">{{form.failuer_date.label}}</label>
    </div>
    <div class="col-2">
        <label for="id_failuer_time" class="form-label">{{form.failuer_time.label}}</label>
    </div>
    <div class="col-3">
        <label for="id_date_time_confirmation" class="form-label">{{form.date_time_confirmation.label}}</label>
    </div>
    <div class="col-5">
        <label for="id_failuer_place" class="form-label">{{form.failuer_place.label}}</label>
    </div>
</div>
<div class="row mt-0">
    <div class="col-2">
        {{form.failuer_date}}
    </div>
    <div class="col-2">
        {{form.failuer_time}}
    </div>
    <div class="col-3">
        {{form.date_time_confirmation}}
    </div>
    <div class="col-5">
        {{form.failuer_place}}
    </div>
</div>
<div class="row form-text">
    <div class="col-12">
        {{form.date_time_confirmation.help_text|safe}}
    </div>
</div>
<div class="row mt-2 mb-0">
    <div class="col-1">
        <label for="id_eq" class="form-label">{{form.eq.label}}</label>
    </div>
    <div class="col-5">
        {{form.eq}}
    </div>
    <div class="col-1">
        <label for="id_department" class="form-label">{{form.department.label}}</label>
    </div>
    <div class="col-5">
        {{form.department}}
    </div>
</div>
<div class="row mt-1">
    <label for="id_sammary" class="form-label">{{form.sammary.label}}</label>
</div>
<div class="row mt-0">
    {{form.sammary}}
</div>
<div class="row mt-1">
    <label for="id_cause" class="form-label">{{form.cause.label}}</label>
</div>
<div class="row mt-0">
    {{form.cause}}
</div>
<div class="row mt-2 mb-0">
    <div class="col-2">
        <label for="id_recovery_date" class="form-label">{{form.recovery_date.label}}</label>
    </div>
    <div class="col-2">
        <label for="id_recovery_time" class="form-label">{{form.recovery_time.label}}</label>
    </div>
</div>
<div class="row mt-0">
    <div class="col-2">
        {{form.recovery_date}}
    </div>
    <div class="col-2">
        {{form.recovery_time}}
    </div>
</div>
<div class="row mt-1">
    <label for="id_recovery_propects" class="form-label">{{form.recovery_propects.label}}</label>
</div>
<div class="row mt-0">
    {{form.recovery_propects}}
</div>
<div class="row mt-1">
    <div class="col-1">
        <label for="id_is_flight_impact" class="form-label">{{form.is_flight_impact.label}}</label>
    </div>
    <div class="col-2">
        {{form.is_flight_impact}}
    </div>
    <div class="col-9">
        {{form.flight_impact}}
    </div>
</div>
<div class="row mt-1">
    <div class="col-1">
        <label for="id_notam" class="form-label">{{form.notam.label}}</label>
    </div>
    <div class="col-11">
        {{form.notam}}
    </div>

</div>
<div class="row mt-1">
    <div class="col-1">
        <label for="id_is_press" class="form-label">{{form.is_press.label}}</label>
    </div>
    <div class="col-2">
        {{form.is_press}}
    </div>
    <div class="col-9">
        {{form.press_contents}}
    </div>
</div>
{{form.select_register}}

rise_info/templates/base_info_add_new_sammary.html
<div class="row mt-2">
    <div class="col-2">
        <label for="id_is_add_eqtypes" class="form-label">{{form.is_add_eqtypes.label}}</label>
        {{form.is_add_eqtypes}}
    </div>
    <div class="col-10">
        <label for="id_eqtypes" class="form-label">{{form.eqtypes.label}}</label>
        {{form.eqtypes}}
    </div>
</div>
<div class="row mt-2">
    <div class="col-2">
        <label for="id_is_add_offices" class="form-label">{{form.is_add_offices.label}}</label>
        {{form.is_add_offices}}
    </div>
    <div class="col-10">
        {{form.offices}}
    </div>
</div>
<div class="row pt-5">
    <div class="col-3">
        <label for="id_info_type" class="form-label">{{form.info_type.label}}</label>
        {{form.info_type}}
    </div>
    <div class="col-9">
        <label for="id_managerID" class="form-label">{{form.managerID.label}}</label>
        {{form.managerID}}
    </div>
</div>
<div class="row">
    <label for="id_sammary" class="form-label">{{form.sammary.label}}</label>
</div>
<div class="row">
    {{form.sammary}}
</div>

rise_info/templates/base_support_add_new_sammary.html
<div class="row mt-2">
    <div class="col-3">
        <label for="id_info_type" class="form-label">{{form.info_type.label}}</label>
        {{form.info_type}}
    </div>
</div>
<div class="row mt-2">
    <div class="col-10">
        <label for="id_eqtypes" class="form-label">{{form.eqtypes.label}}</label>
        {{form.eqtypes}}
    </div>
</div>
<label for="id_inquiry" class="form-label">{{form.inquiry.label}}</label>
{{form.inquiry}}